services:
  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgresql_data_volume
        target: /var/lib/postgresql/data
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    ports:
      - "8080:8080"
    volumes:
      - /workspaces/${RepositoryName}/osm-styles:/opt/geoserver_data
    environment:
      - ROOT_WEBAPP_REDIRECT=true
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS="${CODESPACE_NAME}-8080.app.github.dev,github.dev,localhost,0.0.0.0,127.0.0.1"
      - CORS_ALLOWED_METHODS="GET,POST,PUT,DELETE,HEAD,OPTIONS"
      - CORS_ALLOWED_HEADERS="*"
      - geoserver.xframe.shouldSetPolicy=false
      - geoserver.xContentType.shouldSetPolicy=false
      - GEOSERVER_CSRF_WHITELIST=${CODESPACE_NAME}-8080.app.github.dev
      - GEOSERVER_CSRF_DISABLE=true
      - PROXY_BASE_URL=https://${CODESPACE_NAME}-8080.app.github.dev/geoserver
      - SKIP_DEMO_DATA=true
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=css,feature-pregeneralized

networks:
  default:
    name: gist604b

volumes:
  postgresql_data_volume:
